# -*- coding: utf-8 -*-
"""training_mango_fruit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kU7v8sczmjNJ-Tf7mx3kEA9lmnQ9oGkg
"""

from google.colab import drive
drive.mount('/content/drive')

"""#Importing libraries

"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

"""#Data preprocessing

##training set preprocessing
"""

training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/final ML mango dataset/MangoFruitDDS/train',
    labels = "inferred",
    label_mode = "categorical" ,
    class_names = None,
    color_mode = "rgb" ,
    batch_size = 32,
    image_size = (64,64),
    shuffle = True,
    seed = None,
    validation_split = None,
    subset = None,
    interpolation = "bilinear",
    follow_links = False,
    crop_to_aspect_ratio = False
)

"""##Validation set preprocessing"""

validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/final ML mango dataset/MangoFruitDDS/validation',
    labels = "inferred",
    label_mode = "categorical" ,
    class_names = None,
    color_mode = "rgb" ,
    batch_size = 32,
    image_size = (64,64),
    shuffle = True,
    seed = None,
    validation_split = None,
    subset = None,
    interpolation = "bilinear",
    follow_links = False,
    crop_to_aspect_ratio = False
)

"""#Building model"""

cnn = tf.keras.models.Sequential()

cnn.add(tf.keras.layers.Conv2D(filters = 32, kernel_size = 3, activation='relu' , input_shape =[64 ,64,3]))
cnn.add(tf.keras.layers.Conv2D(filters = 32, kernel_size = 3, activation='relu' ))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

cnn.add(tf.keras.layers.Conv2D(filters = 64, kernel_size = 3, activation='relu' ))
cnn.add(tf.keras.layers.Conv2D(filters = 64, kernel_size = 3, activation='relu' ))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

cnn.add(tf.keras.layers.Flatten())

cnn.add(tf.keras.layers.Dense(units=512,activation='relu'))

cnn.add(tf.keras.layers.Dense(units=256,activation='relu'))

cnn.add(tf.keras.layers.Dropout(0.5))

#output layer
cnn.add(tf.keras.layers.Dense(units=5,activation='softmax'))

"""#compiling and training phase"""

cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

cnn.summary()

training_history = cnn.fit(x = training_set,validation_data = validation_set, epochs=30)

cnn.save('trained_model.h5')

training_history.history

#recording history
import json
with open('training_hist.json','w') as f:
  json.dump(training_history.history,f)

print(training_history.history.keys())

print("validation set accuaracy: {} % ".format(training_history.history['val_accuracy'][-1]*100))

"""#Accuracy visualization

##training visualization
"""

training_history.history['accuracy']

"""#Training accuracy"""

epochs = [i for i in range(1,31)]
plt.plot(epochs,training_history.history['accuracy'],color='red')
plt.xlabel('No of Epochs')
plt.ylabel('Training Accuracy')
plt.title('Visualization of training accuracy result ')
plt.show()

"""#validation Accuracy"""

plt.plot(epochs,training_history.history['val_accuracy'],color='blue')
plt.xlabel('No of Epochs')
plt.ylabel('Validation Accuracy')
plt.title('Visualization of validation accuracy result ')
plt.show()

"""#Training loss"""

epochs = [i for i in range(1,31)]
plt.plot(epochs,training_history.history['loss'],color='green')
plt.xlabel('No of Epochs')
plt.ylabel('Training loss')
plt.title('Visualization of training loss result ')
plt.show()

"""#Validation loss"""

plt.plot(epochs,training_history.history['val_loss'],color='yellow')
plt.xlabel('No of Epochs')
plt.ylabel('Validation loss')
plt.title('Visualization of validation loss result ')
plt.show()

training_loss,training_accuracy = cnn.evaluate(training_set)

val_loss,val_accuracy = cnn.evaluate(validation_set)

test_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/final ML mango dataset/MangoFruitDDS/test',
    labels = "inferred",
    label_mode = "categorical" ,
    class_names = None,
    color_mode = "rgb" ,
    batch_size = 32,
    image_size = (64,64),
    shuffle = True,
    seed = None,
    validation_split = None,
    subset = None,
    interpolation = "bilinear",
    follow_links = False,
    crop_to_aspect_ratio = False
)

test_loss,test_accuracy = cnn.evaluate(test_set)